### PR TITLE
Suggestions

### PR DESCRIPTION
**Pull request by nem5345**
You can tell me to f off if you don't like my ideas.

 - Didn't like trying to tell people a certain language for a website. Allow personal freedom and experimentation. Mostly a JS hater.
 - Added the idea about having your website hosted somewhere in the cloud. Didn't see it mentioned explicitly before.
 - Also time estimate greatly is determined by previous experience. I think a difficulty meter would be much better in determining how much of a commitment a single project will me.

Please accept my ideas as they are the best. Or not, does it even matter.

### CODE REVIEW

**Review by BradHacker — COMMENTED** [review]
I like the changes to the portfolio site.

As for the Idea template update, we strayed away from using "difficulty" as the difficulty of a project is very relative to the skill level of the person doing it. Whereas a "time estimate" is a little more objective.

**Comment by mav8557** [comment]
Agree with @BradHacker on the difficulty - it's meant to imply that you have a first-year computing background and have heard of what the project description is about, like from Wikipedia, but only have a high-level understanding of how it works and want to create it for yourself. If you have that, it's meant to answer how long it would take you to get an MVP relative to the other projects in the list.

There's nothing truly objective about it, but that's a reasonable way for someone to go about reading these and is what I had in mind. It doesn't factor in the time it takes fixing bugs that inevitably come up when you develop things, but rather if you have few big bugs, how long would it take for you to actually create that MVP.

As for the portfolio site using JS is not a requirement, the going further section is just for potential extension ideas. If you want to extend that project, that section has ways that might be of interest. Important thing also is that this describes a static site, so using Python/Go/Rust don't really apply.|

That being said for you and anyone else interested in proposing additional projects to this repository, we would definitely like to add them. More is better than fewer, so that we can get as many ideas as possible into one place for people looking to learn.

**Comment by nem5345** [comment]
Great response, this clarifies the time required field. As long as the time
required field takes in to consideration the time it would take a new
security student to complete the project I think it’s a completely fine
metric. I agree it’s super difficult to become objective with a difficulty
with projects especially without knowledge. However, that’s why I was
trying to suggest instead a “previous knowledge required” specificity.
Because, if you included a previous knowledge category, students could
research those topics until they are knowledgeable enough to complete the
project idea.

**Comment by mav8557** [comment]
Good idea, I'll look into defining this in the repository somewhere everyone will see it - right now we only mention what the time estimate means in the CONTRIBUTING.md file. I definitely wouldn't want someone new to see these estimates and think they aren't skilled enough because they took eight hours on a project when it was 'estimated' to be two. They don't really make sense without relating to each other IMO.

Previous knowledge required is a good idea also. What do you think about dropping 'required' and calling it a focus area? Something like:

### Focus Areas
- Active Directory
- Subnetting
- DNS

The idea being that it's fuzzy, so if you like the project  you have an idea of what to expect and what it would help to be familiar with. Maybe ordered loosely in order of importance.

**Comment by BradHacker** [comment]
I like the "Focus Area" name @mav8557.

Understand the argument both ways honestly. I think we should ask folks to rate time required relative to the prerequisite knowledge required for the project (also a good addition @nem5345). So if a project requires familiarity with HTML/JS/CSS, assume the student has just learned these topics and go on that.

**Comment by nem5345** [comment]
I really like the "Focus Area" name as well. I think it best describes what we are saying. The whole idea was to give students a realistic idea of what to expect. Focus area would also give the possibility of representing projects by focus area as well. For example, there is the beginners list. Something similar could be done for each Focus Area once they are more ideas etc. 

Definitely a sentence that asks folks to rate time required relative to the perquisite within the Contributing.md would go a long way. Brad summarized pretty much what I was thinking.

**Pull request merged**
